version: '2.1'
orbs:
  macos: circleci/macos@2.1.0
jobs:
  test-install-macos:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: echo 'chruby ruby-2.7' >> ~/.bash_profile
      - run:
          name: Run sanity test of R wrapper
          command: | # this doesn't cache dependencies, and takes quite a while – todo: optimize
            NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bash_profile
            eval "$(/opt/homebrew/bin/brew shellenv)"
            brew install r -f
            R --no-save \<<code
            install.packages('devtools', repos = "http://cran.us.r-project.org")
            devtools::install_github('trytoolchest/toolchest-client-r', ref='$CIRCLE_BRANCH')
            library(toolchest)

            code
  test-install-rocker-devtools:
    docker:
      - image: rocker/tidyverse:4.2
    steps:
      - checkout
      - run:
          name: Run sanity test of R wrapper
          command: |
            R --no-save \<<code
            install.packages("devtools")
            devtools::install_github('trytoolchest/toolchest-client-r', ref='$CIRCLE_BRANCH', dependencies=T, upgrade_dependencies=T)
            library(toolchest)

            code
workflows:
    test:
      jobs:
        - test-install-rocker-devtools:
            filters:
              branches:
                only:
                  - main
                  - staging
                  - feat/redo-install

