version: 2.1
jobs:
  test:
    docker:
      - image: rocker/rstudio:latest
    steps:
      - checkout
      - run:
          name: Run sanity test of R wrapper
          command: |
            R -e "devtools::install_github('trytoolchest/toolchest-client-r', ref='$CIRCLE_BRANCH')"
            R -e "library(toolchest)"

workflows:
  version: 2
  test_basic_install:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - staging
